#ism=input("Atinin'izdi kiritin'\n>>>").title().strip()
#print(f"Salem {ism} siz benen tanisqniman quwanishliman")
#fam=input(f"Iltimas {ism} familyan'izdi kiritsen'iz\n>>>").title().strip()
#print(f"{fam} {ism} sizge qanday jardem bere alaman")
koshe=input("Koshen'izdi kiritin'>>>").title().strip()
mahalle=input("Mahallen'izdi kiritin'>>>").title().strip()
tuman=input("Tumanin'izdi kiritin'>>>").title().strip()
viloyat=input("Viloyatin'izdi kiritin'>>>").title().strip()
print(koshe +" "+ "koshesi,\n" +" "+ mahalle +" " + "mahallesi,\n" +" "+ tuman +" "+ "tumani,\n" +" "+ viloyat +" "+ "viloyati")