print("Assalom alaykum")
print("Ilimnen ozge najot joq \nNajot talimda")
print("Men \"Dell\" markali noutbok satip aldim")
print(4+5*9)
print(4**(2/4))
print(15%6)
print("\"Nexia\" , \"Tico\", \'Damas\' ko'rganlar qilar havas.")
print("Tomonlari 125 ga ten' bolgan kvadrat yuzi" , 125*125, "ga ten' peremetri" ,125+125 ,"ga ten'")
print("Diametri 12 ga ten' bolgan doira yuzi", 2*3.14*12, " ge ten'")